on:
  workflow_call:
    inputs:
      docker-registry:
        required: true
        type: string
      google-project-id:
        required: true
        type: string
      workload-identity-provider:
        required: true
        type: string
      service-account-email:
        required: true
        type: string
      self-url:
        required: false
        type: string
      log-level:
        required: false
        type: string
        default: info

jobs:
  deploy-to-cloud-run:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Authenticate to GCP 🔒
        uses: google-github-actions/auth@v0
        with:
          project_id: ${{ inputs.google-project-id }}
          workload_identity_provider: ${{ inputs.workload-identity-provider }}
          service_account: ${{ inputs.service-account-email }}

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images:
            ${{ inputs.docker-registry }}/${{ github.event.repository.name }}
          flavor: latest=true
          tags: |
            type=sha,prefix={{branch}}-
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from:
            type=registry,ref=${{ inputs.docker-registry }}/${{
            github.event.repository.name }}:latest
          cache-to: type=inline

      - uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ github.event.repository.name }}
          image:
            ${{ inputs.docker-registry }}/${{ github.event.repository.name
            }}:${{ steps.meta.outputs.version }}
          region: europe-north1
          env_vars:
            LOG_LEVEL=${{ inputs.log-level }},SELF_URL=${{ inputs.self-url }}
