# fly.toml app configuration file generated for branches-unleash on 2024-11-14T14:04:53+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'branches-unleash'
primary_region = 'arn'

[build]
  image = 'unleashorg/unleash-server:6.2.0'

[env]
  DATABASE_SSL = 'false'
  UNLEASH_URL = 'https://branches-unleash.fly.dev/'

[http_service]
  internal_port = 4242
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    path = '/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1