on:
  workflow_call:
    inputs:
      self-url:
        required: false
        type: string
      log-level:
        required: false
        type: string
        default: info
    secrets:
      DOCKER_REPOSITORY:
        required: true
      GOOGLE_PROJECT_ID:
        required: true
      WORKLOAD_IDENTITY_PROVIDER:
        required: true
      SERVICE_ACCOUNT_EMAIL:
        required: true

jobs:
  deploy-to-cloud-run:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Authenticate to GCP 🔒
        uses: google-github-actions/auth@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images:
            ${{ secrets.DOCKER_REPOSITORY }}/${{ github.event.repository.name }}
          flavor: latest=true
          tags: |
            type=sha,prefix={{branch}}-
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from:
            type=registry,ref=${{ secrets.DOCKER_REPOSITORY }}/${{
            github.event.repository.name }}:latest
          cache-to: type=inline

      - uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ github.event.repository.name }}
          image:
            ${{ secrets.DOCKER_REPOSITORY }}/${{ github.event.repository.name
            }}:${{ steps.meta.outputs.version }}
          region: europe-north1
          env_vars:
            LOG_LEVEL=${{ inputs.log-level }},SELF_URL=${{ inputs.self-url }}
