name: Preview changes

permissions:
  id-token: write
  contents: read
  pull-requests: write

on:
  pull_request:
    paths:
      - resources/**
      - Pulumi.*
      - yarn.lock
      - package.json
      - .github/workflows/*.yml

run-name: Preview branches/branches-main/main by @${{ github.actor }}

jobs:
  pulumi:
    name: Pulumi
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Node LTS ✨
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn

      - name: Installing dependencies 📦️
        run: yarn install

      - name: Authenticate to GCP 🔒
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: conf-deployer@bjerk-core.iam.gserviceaccount.com

      - uses: simenandre/setup-gke-gcloud-auth-plugin@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::318306939417:role/GitHubActionRole
          aws-region: eu-north-1

      - name: Running Pulumi 🚀
        uses: pulumi/actions@v4
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        with:
          command: preview
          comment-on-pr: true
          stack-name: branches/branches-main/main
