name: Preview changes

permissions:
  id-token: write
  contents: read

on:
  pull_request:

run-name: Preview branches/branches-main/main by @${{ github.actor }}

jobs:
  apply-infra:
    name: Apply infrastructure
    uses: getbranches/conf/.github/workflows/pulumi-workflow.yml@boilerplate-pulumi
    with:
      environment: main
      command: preview
    secrets: inherit
