name: Preview changes

permissions:
  id-token: write
  contents: read
  pull-requests: write

on:
  pull_request:

run-name: Preview branches/branches-main/main by @${{ github.actor }}

jobs:
  preview-infra:
    name: Preview infrastructure
    uses: getbranches/conf/.github/workflows/pulumi-workflow.yml@boilerplate-pulumi
    with:
      environment: main
      command: preview
    secrets: inherit
