name: Apply changes

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main

jobs:
  apply-infra:
    name: Apply infrastructure
    uses: getbranches/conf/.github/workflows/pulumi-workflow.yml@main
    with:
      environment: main
    secrets: inherit
