name: Workflow

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - master

jobs:
  apply-infra:
    name: Apply infrastructure
    uses: getbranches/conf/pulumi-workflow.yml@main
    with:
      environment: main
    secrets: inherit
