name: Apply changes

permissions:
  id-token: write
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main

run-name: Apply branches/branches-main/main by @${{ github.actor }}

jobs:
  apply-infra:
    name: Apply infrastructure
    uses: getbranches/conf/.github/workflows/pulumi-workflow.yml@main
    with:
      environment: main
    secrets: inherit
